---
- name: ensure operations account exists
  user: >
    name={{ ops_account_username }}
    createhome=yes
    generate_ssh_key=yes
    shell={{ ops_account_shell }}
    state=present
- name: ensure operations account has authorized_keys file
  copy: >
    content="{{ lookup('file', my_ssh_public_key_file) }}"
    dest={{ ops_account_ssh_authorized_keys_file }}
    owner={{ ops_account_username }}
    group={{ ops_account_username }}
    mode={{ ops_account_ssh_authorized_keys_permissions }}
- name: add operations account to sudoers
  template: >
    src=sudoers.j2
    dest={{ ops_account_sudoers_file }}
    owner={{ ops_account_sudoers_owner }}
    group={{ ops_account_sudoers_group }}
    mode={{ ops_account_sudoers_permissions }}
    validate="visudo -cf %s"

