---
- name: ensure root is no longer allowed to login
  template: >
    src=sshd_config.j2
    dest=/etc/ssh/sshd_config
    owner=root
    group=root
    mode=644
    validate="/usr/sbin/sshd -T -f %s"
  notify: restart ssh

